import { type Recipe, RecipeCategory } from "@/types/recipe"

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Classic Margherita Pizza",
    image: "/placeholder.svg?height=300&width=400",
    ingredients: [
      "Pizza dough (1 ball)",
      "Tomato sauce (1/2 cup)",
      "Fresh mozzarella (8 oz)",
      "Fresh basil leaves (10)",
      "Olive oil (2 tbsp)",
      "Salt (1/2 tsp)",
    ],
    instructions: [
      "Preheat oven to 475°F (245°C) with a pizza stone inside.",
      "Roll out the pizza dough on a floured surface to your desired thickness.",
      "Spread tomato sauce evenly over the dough, leaving a small border for the crust.",
      "Tear the mozzarella into pieces and distribute evenly over the sauce.",
      "Bake for 10-12 minutes until the crust is golden and the cheese is bubbly.",
      "Remove from oven, top with fresh basil leaves, drizzle with olive oil, and sprinkle with salt.",
    ],
    cuisine: "Italian",
    prepTime: "20 minutes",
    cookTime: "12 minutes",
    mealType: "Dinner",
    dietary: "Vegetarian",
    category: RecipeCategory.Vegetarian,
    servings: 4,
    createdAt: new Date(),
    isFavorite: true,
    isPopular: true,
    isSeasonal: false,
  },
  {
    id: "2",
    title: "Avocado Toast with Poached Egg",
    image: "/placeholder.svg?height=300&width=400",
    ingredients: [
      "Bread (2 slices)",
      "Ripe avocado (1)",
      "Eggs (2)",
      "Lemon juice (1 tsp)",
      "Red pepper flakes (1/4 tsp)",
      "Salt (1/4 tsp)",
      "Black pepper (1/4 tsp)",
    ],
    instructions: [
      "Toast the bread slices until golden brown.",
      "In a small bowl, mash the avocado with lemon juice, salt, and pepper.",
      "Bring a pot of water to a gentle simmer. Add a splash of vinegar.",
      "Crack an egg into a small cup, then gently slide it into the simmering water.",
      "Poach for 3-4 minutes until whites are set but yolk is still runny.",
      "Spread mashed avocado on toast, top with poached egg, and sprinkle with red pepper flakes.",
    ],
    cuisine: "American",
    prepTime: "10 minutes",
    cookTime: "5 minutes",
    mealType: "Breakfast",
    dietary: "Vegetarian",
    category: RecipeCategory["Breakfast Favorites"],
    servings: 2,
    createdAt: new Date(),
    isFavorite: false,
    isPopular: true,
    isSeasonal: true,
  },
  {
    id: "3",
    title: "Thai Green Curry",
    image: "/placeholder.svg?height=300&width=400",
    ingredients: [
      "Green curry paste (2 tbsp)",
      "Coconut milk (14 oz)",
      "Chicken breast (1 lb)",
      "Bell peppers (2)",
      "Bamboo shoots (1 cup)",
      "Fish sauce (1 tbsp)",
      "Brown sugar (1 tbsp)",
      "Thai basil leaves (1/2 cup)",
      "Lime leaves (4)",
    ],
    instructions: [
      "In a large pot, heat 1 tablespoon of oil over medium heat.",
      "Add green curry paste and cook for 1 minute until fragrant.",
      "Add coconut milk and bring to a simmer.",
      "Add sliced chicken and cook for 5 minutes.",
      "Add bell peppers, bamboo shoots, fish sauce, and brown sugar.",
      "Simmer for 10 minutes until chicken is cooked through.",
      "Stir in Thai basil leaves and lime leaves before serving.",
    ],
    cuisine: "Thai",
    prepTime: "15 minutes",
    cookTime: "20 minutes",
    mealType: "Dinner",
    category: RecipeCategory["International Cuisine"],
    servings: 4,
    createdAt: new Date(),
    isFavorite: true,
    isPopular: true,
    isSeasonal: false,
  },
  {
    id: "4",
    title: "Chocolate Chip Cookies",
    image: "/placeholder.svg?height=300&width=400",
    ingredients: [
      "All-purpose flour (2 1/4 cups)",
      "Baking soda (1 tsp)",
      "Salt (1 tsp)",
      "Butter (1 cup)",
      "Brown sugar (3/4 cup)",
      "Granulated sugar (3/4 cup)",
      "Vanilla extract (1 tsp)",
      "Eggs (2)",
      "Chocolate chips (2 cups)",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "In a small bowl, mix flour, baking soda, and salt.",
      "In a large bowl, beat butter, brown sugar, granulated sugar, and vanilla until creamy.",
      "Add eggs one at a time, beating well after each addition.",
      "Gradually beat in flour mixture.",
      "Stir in chocolate chips.",
      "Drop by rounded tablespoon onto ungreased baking sheets.",
      "Bake for 9-11 minutes until golden brown.",
      "Cool on baking sheets for 2 minutes, then transfer to wire racks.",
    ],
    cuisine: "American",
    prepTime: "15 minutes",
    cookTime: "10 minutes",
    mealType: "Dessert",
    dietary: "Vegetarian",
    category: RecipeCategory["Comfort Food"],
    servings: 24,
    createdAt: new Date(),
    isFavorite: false,
    isPopular: true,
    isSeasonal: false,
  },
  {
    id: "5",
    title: "Grilled Steak with Herb Butter",
    image: "/placeholder.svg?height=300&width=400",
    ingredients: [
      "Ribeye steaks (2, 1-inch thick)",
      "Salt (2 tsp)",
      "Black pepper (1 tsp)",
      "Garlic powder (1 tsp)",
      "Unsalted butter (4 tbsp)",
      "Fresh rosemary (1 tbsp, chopped)",
      "Fresh thyme (1 tbsp, chopped)",
      "Garlic (2 cloves, minced)",
    ],
    instructions: [
      "Remove steaks from refrigerator 30 minutes before cooking to bring to room temperature.",
      "Mix salt, pepper, and garlic powder and season steaks generously on both sides.",
      "Preheat grill to high heat (about 450-500°F).",
      "While grill heats, mix softened butter with chopped herbs and minced garlic.",
      "Grill steaks for 4-5 minutes per side for medium-rare.",
      "Remove steaks from grill and let rest for 5 minutes.",
      "Top each steak with a tablespoon of herb butter and serve immediately.",
    ],
    cuisine: "American",
    prepTime: "10 minutes",
    cookTime: "10 minutes",
    mealType: "Dinner",
    category: RecipeCategory["Meat Lovers"],
    servings: 2,
    createdAt: new Date(),
    isFavorite: true,
    isPopular: true,
    isSeasonal: false,
  },
  {
    id: "6",
    title: "Quick Greek Salad",
    image: "/placeholder.svg?height=300&width=400",
    ingredients: [
      "Cucumber (1 large)",
      "Tomatoes (4 medium)",
      "Red onion (1/2)",
      "Green bell pepper (1)",
      "Kalamata olives (1/2 cup)",
      "Feta cheese (200g)",
      "Olive oil (1/4 cup)",
      "Red wine vinegar (2 tbsp)",
      "Dried oregano (1 tsp)",
      "Salt (1/2 tsp)",
      "Black pepper (1/4 tsp)",
    ],
    instructions: [
      "Dice cucumber, tomatoes, red onion, and green bell pepper into bite-sized pieces.",
      "Combine vegetables in a large bowl.",
      "Add Kalamata olives.",
      "Crumble feta cheese over the top.",
      "In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper.",
      "Pour dressing over the salad and toss gently to combine.",
      "Serve immediately or refrigerate for up to 1 hour before serving.",
    ],
    cuisine: "Greek",
    prepTime: "15 minutes",
    cookTime: "0 minutes",
    mealType: "Lunch",
    dietary: "Vegetarian",
    category: RecipeCategory["Quick & Easy"],
    servings: 4,
    createdAt: new Date(),
    isFavorite: false,
    isPopular: false,
    isSeasonal: true,
  },
]

